version: "3"

services:
  base-api:
    extends:
      file: docker-compose.app.yml
      service: base-api
    depends_on:
      - qdrant
      - pgdb
      - redis
      - minio
    networks:
      - my-network

  qdrant:
    image: qdrant/qdrant:v1.1.3
    mem_limit: 450m
    ports:
      - "0.0.0.0:${QDRANT_PORT}:6333"
    volumes:
      - ./data/qdrant_storage:/qdrant/storage
    networks:
      - my-network

  pgdb:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - type: volume
        source: pgdb-data
        target: "/var/lib/postgresql/data"
    ports:
      - "0.0.0.0:${DBPORT}:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - type: volume
        source: pgadmin-data
        target: /root/.pgadmin
    restart: unless-stopped
    ports:
      - "0.0.0.0:${PGADMIN_PORT}:5050"
    networks:
      - my-network

  redis:
    image: "redis:6"
    user: "999:999"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
    networks:
      - my-network

  redis-ui:
    image: patrikx3/p3x-redis-ui:latest
    depends_on:
      - redis
    ports:
      - 0.0.0.0:${REDIS_UI_PORT}:7843
    volumes:
      - p3x-redis-ui-settings:/settings
    networks:
      - my-network

  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: 'root'
      MINIO_ROOT_PASSWORD: 'password'
    volumes:
      - 'minio:/data/minio'
    command: minio server /data/minio --console-address ":9090"
    networks:
      - my-network

volumes:
  pgdb-data:
  pgadmin-data:
  redis-data:
  redis-conf:
  p3x-redis-ui-settings:
  minio:
  node_modules:

networks:
  my-network:
